ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [io.titlis.api.MainKt.module]
    }
}

titlis {
    database {
        url      = "jdbc:postgresql://localhost:5432/titlis"
        url      = ${?DATABASE_URL}
        user     = "titlis"
        user     = ${?DATABASE_USER}
        password = "titlis"
        password = ${?DATABASE_PASSWORD}
        pool {
            maxPoolSize       = 10
            maxPoolSize       = ${?DB_POOL_MAX}
            connectionTimeout = 30000
            idleTimeout       = 600000
        }
    }
    udp {
        port        = 8125
        port        = ${?TITLIS_UDP_PORT}
        bufferSize  = 65507   # max UDP payload IPv4
        workers     = 4       # coroutines processando a fila
        queueSize   = 10000   # buffer interno antes de processar
    }
}