package io.titlis.api.routes

import io.titlis.api.domain.CoverageDimensionDTO
import io.titlis.api.domain.CoverageFindingDTO
import io.titlis.api.domain.CoverageResultDTO
import io.titlis.api.repository.CoverageRepository
import kotlinx.coroutines.test.runTest
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.transactions.transaction
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

// E2E da fatia D5b/D5e: grafo ingerido (discovered_asset/asset_relation) → CoverageRepository monta
// o CoverageSnapshot por natureza → persiste/lê o resultado. jsonb modelado como TEXT no H2.
class CoverageE2ETest {

    private lateinit var db: Database
    private val repo = CoverageRepository()

    @BeforeTest
    fun setup() {
        db = Database.connect(
            url = "jdbc:h2:mem:test_cov_${System.nanoTime()};DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
            driver = "org.h2.Driver",
        )
        transaction(db) {
            exec("CREATE SCHEMA IF NOT EXISTS titlis_oltp")
            exec(
                """CREATE TABLE titlis_oltp.discovered_asset (
                    discovered_asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, provider TEXT NOT NULL, kind TEXT NOT NULL,
                    external_id TEXT NOT NULL, name TEXT NOT NULL, namespace TEXT, cluster_name TEXT,
                    tags TEXT NOT NULL DEFAULT '{}', attributes TEXT NOT NULL DEFAULT '{}',
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW())""",
            )
            exec(
                """CREATE TABLE titlis_oltp.asset_relation (
                    asset_relation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, source_discovered_asset_id BIGINT NOT NULL,
                    target_discovered_asset_id BIGINT NOT NULL, relation_type TEXT NOT NULL,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW())""",
            )
            exec(
                """CREATE TABLE titlis_oltp.coverage_scorecard (
                    coverage_scorecard_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, workload_uid TEXT NOT NULL, service_name TEXT,
                    cluster_name TEXT, trust_score NUMERIC(5,2),
                    coverage_json TEXT NOT NULL DEFAULT '[]', findings_json TEXT NOT NULL DEFAULT '[]',
                    evaluated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW())""",
            )
            // H1 — service-map: estrutura do .titlis/service.yaml (service_definitions) + correlação
            // materializada em workloads.service_definition_id.
            exec(
                """CREATE TABLE titlis_oltp.service_definitions (
                    service_definition_id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL,
                    service_name TEXT NOT NULL, team TEXT NOT NULL, product TEXT, tier TEXT, repo_url TEXT)""",
            )
            exec(
                """CREATE TABLE titlis_oltp.workloads (
                    workload_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    k8s_uid TEXT, service_definition_id BIGINT)""",
            )
            exec(
                "INSERT INTO titlis_oltp.service_definitions " +
                    "(service_definition_id, tenant_id, service_name, team, product, repo_url) VALUES " +
                    "(100,1,'orders','squad-pag','checkout','https://github.com/org/orders')",
            )
            // dep-1 correlacionado ao service_definition 100; dep-2/dep-3 sem service.yaml → órfãos.
            exec(
                "INSERT INTO titlis_oltp.workloads (workload_id, k8s_uid, service_definition_id) VALUES " +
                    "(1,'dep-1',100),(2,'dep-2',NULL),(3,'dep-3',NULL)",
            )

            val attrs = """{"cpuRequestSet":true,"cpuLimitSet":true,"memoryRequestSet":true,"memoryLimitSet":true,"hasLivenessProbe":true,"hasReadinessProbe":true,"ddService":"orders"}"""
            val ddSvcAttrs = """{"capabilities":["tracing","metrics"],"metricCategories":["http","jvm"]}"""
            exec(
                "INSERT INTO titlis_oltp.discovered_asset " +
                    "(discovered_asset_id, tenant_id, provider, kind, external_id, name, namespace, cluster_name, attributes) VALUES " +
                    "(1,1,'kubernetes','deployment','dep-1','orders-api','shop','c','$attrs')," +
                    "(2,1,'kubernetes','service','svc-1','orders-svc','shop','c','{}')," +
                    "(3,1,'kubernetes','networkpolicy','np-1','default-deny','shop','c','{}')," +
                    "(4,1,'kubernetes','hpa','hpa-1','orders-hpa','shop','c','{}')," +
                    "(5,1,'datadog','dd_service','service:orders','orders',NULL,NULL,'$ddSvcAttrs')," +
                    "(6,1,'datadog','dd_monitor','monitor:1','orders backlog',NULL,NULL,'{}')," +
                    "(7,1,'kubernetes','deployment','dep-2','ledger','shop','c','{}')," +
                    "(8,1,'kubernetes','deployment','dep-3','signup','shop','c','{}')",
            )
            // workload soft-deletado (is_active=false) — seu scorecard NÃO deve aparecer na leitura.
            exec(
                "INSERT INTO titlis_oltp.discovered_asset " +
                    "(discovered_asset_id, tenant_id, provider, kind, external_id, name, cluster_name, is_active) VALUES " +
                    "(9,1,'kubernetes','deployment','dep-gone','gone','c',FALSE)",
            )
            exec(
                "INSERT INTO titlis_oltp.asset_relation " +
                    "(tenant_id, source_discovered_asset_id, target_discovered_asset_id, relation_type) VALUES " +
                    "(1,2,1,'selects')," + // service selects deployment → httpFacing
                    "(1,1,4,'scaled_by')," + // deployment scaled_by hpa → hasHpa
                    "(1,5,1,'describes')," + // dd_service descreve o deployment (Correlator)
                    "(1,6,5,'monitors')", // dd_monitor monitora o dd_service → capability monitor (2-hop)
            )
        }
    }

    @Test
    fun `buildSnapshots deriva natureza e found do grafo`() = runTest {
        val snaps = repo.buildSnapshots(1)
        // dep-1/dep-2/dep-3 são deployments ativos; dep-gone é inativo (excluído da query).
        assertTrue(snaps.none { it.workloadUid == "dep-gone" }, "workload inativo não entra no sweep")
        val s = snaps.first { it.workloadUid == "dep-1" }

        assertEquals("dep-1", s.workloadUid)
        assertEquals("orders", s.serviceName) // do atributo ddService (USTag)
        assertEquals("shop", s.namespace)
        assertEquals("c", s.cluster)

        assertTrue(s.nature.httpFacing, "service selects → httpFacing")
        assertFalse(s.nature.stateful)
        assertFalse(s.nature.scheduled)

        assertTrue(s.found.cpuRequestSet)
        assertTrue(s.found.memoryLimitSet)
        assertTrue(s.found.hasProbes)
        assertTrue(s.found.hasHpa, "scaled_by → hasHpa")
        assertTrue(s.found.hasNetworkPolicy, "networkpolicy no namespace")
        assertFalse(s.found.hasPdb)

        // Capability-gating (opção B): dd_monitor→dd_service→workload (2-hop) acende "monitor";
        // o dd_service anota tracing/metrics + categorias → fluem para o snapshot.
        assertTrue("monitor" in s.capabilities, "2-hop dd_monitor → capability monitor")
        assertTrue("tracing" in s.capabilities)
        assertTrue("metrics" in s.capabilities)
        assertTrue(s.found.hasMonitor, "2-hop → hasMonitor")
        assertTrue(s.found.hasTracing)
        assertTrue(s.found.metricCategories.containsAll(listOf("http", "jvm")))
    }

    @Test
    fun `upsertResult e listForTenant fazem round-trip do scorecard`() = runTest {
        val result = CoverageResultDTO(
            workloadUid = "dep-1", serviceName = "orders", cluster = "c", tenantId = 1,
            engineSlug = "coverage", trustScore = 75.0,
            findings = listOf(
                CoverageFindingDTO(code = "COV-RESOURCES", pillar = "performance", severity = "error", weight = 10.0, outcome = "pass", message = "ok"),
                CoverageFindingDTO(code = "COV-TRACING", pillar = "observability", severity = "warning", weight = 6.0, outcome = "na", message = "datadog off"),
            ),
            dimensions = listOf(
                CoverageDimensionDTO(pillar = "performance", evaluable = 1, passed = 1, na = 0, pct = 100.0, maturityLevel = 5),
                CoverageDimensionDTO(pillar = "resilience", evaluable = 2, passed = 1, na = 0, pct = 50.0, maturityLevel = 2),
            ),
        )
        repo.upsertResult(result)
        // idempotente: reaplicar não duplica
        repo.upsertResult(result.copy(trustScore = 80.0))

        val list = repo.listForTenant(1)
        assertEquals(1, list.size)
        val sc = list.first()
        assertEquals("dep-1", sc.workloadUid)
        assertEquals(80.0, sc.trustScore)
        assertEquals(2, sc.findings.size)
        assertTrue(sc.findings.any { it.code == "COV-RESOURCES" && it.outcome == "pass" })
        assertTrue(sc.findings.any { it.code == "COV-TRACING" && it.outcome == "na" })
        assertEquals(2, sc.dimensions.size)
        assertEquals(2, sc.maturity) // elo mais fraco: resilience nível 2
    }

    @Test
    fun `topRisks ordena por menor trust score`() = runTest {
        repo.upsertResult(CoverageResultDTO(workloadUid = "dep-1", serviceName = "orders", cluster = "c", tenantId = 1, trustScore = 90.0))
        repo.upsertResult(CoverageResultDTO(workloadUid = "dep-2", serviceName = "ledger", cluster = "c", tenantId = 1, trustScore = 40.0))
        repo.upsertResult(CoverageResultDTO(workloadUid = "dep-3", serviceName = "signup", cluster = "c", tenantId = 1, trustScore = 65.0))

        val top = repo.topRisks(1, 2)
        assertEquals(2, top.size)
        assertEquals("dep-2", top[0].workloadUid) // 40 = pior
        assertEquals("dep-3", top[1].workloadUid) // 65 = segundo pior
    }

    @Test
    fun `leitura exclui scorecard de workload soft-deletado (regra 13)`() = runTest {
        // dep-1 ativo; dep-gone foi soft-deletado (is_active=false) no seed.
        repo.upsertResult(CoverageResultDTO(workloadUid = "dep-1", serviceName = "orders", cluster = "c", tenantId = 1, trustScore = 80.0))
        repo.upsertResult(CoverageResultDTO(workloadUid = "dep-gone", serviceName = "gone", cluster = "c", tenantId = 1, trustScore = 10.0))

        val uids = repo.listForTenant(1).map { it.workloadUid }
        assertTrue("dep-1" in uids, "workload ativo permanece")
        assertFalse("dep-gone" in uids, "scorecard de workload inativo é excluído")

        val topUids = repo.topRisks(1, 10).map { it.workloadUid }
        assertFalse("dep-gone" in topUids, "top-risks também exclui inativo")
    }

    @Test
    fun `buildServiceMap monta arvore por service-yaml e bucket de orfaos`() = runTest {
        repo.upsertResult(CoverageResultDTO(workloadUid = "dep-1", serviceName = "orders", cluster = "c", tenantId = 1, trustScore = 80.0))
        repo.upsertResult(CoverageResultDTO(workloadUid = "dep-2", serviceName = "ledger", cluster = "c", tenantId = 1, trustScore = 40.0))
        repo.upsertResult(CoverageResultDTO(workloadUid = "dep-3", serviceName = "signup", cluster = "c", tenantId = 1, trustScore = 60.0))

        val map = repo.buildServiceMap(1)

        // dep-1 correlacionado via .titlis/service.yaml → produto → squad → serviço
        assertEquals(1, map.products.size)
        val product = map.products.first()
        assertEquals("checkout", product.product)
        assertEquals(1, product.squads.size)
        val squad = product.squads.first()
        assertEquals("squad-pag", squad.team)
        val service = squad.services.first()
        assertEquals("orders", service.serviceName)
        assertEquals("https://github.com/org/orders", service.repoUrl)
        assertEquals(listOf("dep-1"), service.workloads.map { it.workloadUid })
        assertEquals(80.0, service.workloads.first().score)
        assertEquals(80.0, squad.score) // média de 1 workload

        // dep-2/dep-3 sem service.yaml → órfãos (driver de adoção)
        assertEquals(setOf("dep-2", "dep-3"), map.orphans.map { it.workloadUid }.toSet())
    }
}
