package io.titlis.api.routes

import io.ktor.client.request.get
import io.ktor.client.request.header
import io.ktor.client.statement.bodyAsText
import io.ktor.http.HttpStatusCode
import io.ktor.server.testing.testApplication
import io.titlis.api.domain.ReliabilityNodeDTO
import io.titlis.api.repository.ReliabilityRepository
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.transactions.transaction
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

// Unidade pura do rollup — pesos e poda, sem banco.
class ReliabilityRollupUnitTest {

    @Test
    fun `tierWeight mapeia tiers para pesos`() {
        assertEquals(3.0, ReliabilityRepository.tierWeight("tier-1"))
        assertEquals(3.0, ReliabilityRepository.tierWeight("HIGH"))
        assertEquals(2.0, ReliabilityRepository.tierWeight("tier-2"))
        assertEquals(1.0, ReliabilityRepository.tierWeight(null))
        assertEquals(1.0, ReliabilityRepository.tierWeight("tier-3"))
    }

    @Test
    fun `sliceTree poda filhos por depth e acha por path`() {
        val service = ReliabilityNodeDTO(path = "checkout/team/10", kind = "service", name = "svc", hasChildren = true)
        val team = ReliabilityNodeDTO(path = "checkout/team", kind = "team", name = "team", hasChildren = true, children = listOf(service))
        val product = ReliabilityNodeDTO(path = "checkout", kind = "product", name = "checkout", hasChildren = true, children = listOf(team))
        val root = ReliabilityNodeDTO(path = "", kind = "estate", name = "Estate", hasChildren = true, children = listOf(product))

        // depth=1 a partir da raiz → só produtos, sem times
        val d1 = ReliabilityRepository.sliceTree(root, "", 1)!!
        assertEquals(1, d1.children.size)
        assertTrue(d1.children.first().children.isEmpty())

        // navega até o produto, depth=1 → times aparecem
        val prod = ReliabilityRepository.sliceTree(root, "checkout", 1)!!
        assertEquals("product", prod.kind)
        assertEquals(1, prod.children.size)
        assertEquals("team", prod.children.first().kind)

        // path inexistente → null
        assertEquals(null, ReliabilityRepository.sliceTree(root, "nope", 1))
    }
}

// E2E de backend: HTTP → rota → ReliabilityRepository real → H2.
class ReliabilityE2ETest {

    private lateinit var db: Database

    @BeforeTest
    fun setup() {
        db = Database.connect(
            url = "jdbc:h2:mem:test_reliab_${System.nanoTime()};DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
            driver = "org.h2.Driver",
        )
        transaction(db) {
            exec("CREATE SCHEMA IF NOT EXISTS titlis_oltp")
            exec("CREATE SCHEMA IF NOT EXISTS titlis_ts")
            exec("""CREATE TABLE titlis_oltp.service_definitions (
                service_definition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id BIGINT NOT NULL, service_name TEXT NOT NULL, team TEXT NOT NULL,
                product TEXT, tier TEXT)""")
            exec("""CREATE TABLE titlis_oltp.workloads (
                workload_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                workload_name VARCHAR(255) NOT NULL, k8s_uid VARCHAR(255), service_definition_id BIGINT, is_active BOOLEAN NOT NULL DEFAULT TRUE)""")
            exec("""CREATE TABLE titlis_ts.scorecard_scores (
                scorecard_score_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                workload_id BIGINT NOT NULL, tenant_id BIGINT, overall_score NUMERIC(5,2) NOT NULL,
                recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW())""")
            exec("""CREATE TABLE titlis_oltp.app_scorecards (
                app_scorecard_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                workload_id BIGINT NOT NULL, tenant_id BIGINT, overall_score NUMERIC(5,2) NOT NULL)""")
            exec("""CREATE TABLE titlis_oltp.queues (
                queue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id BIGINT NOT NULL, display_name VARCHAR(255) NOT NULL,
                service_definition_id BIGINT, is_active BOOLEAN NOT NULL DEFAULT TRUE)""")
            exec("""CREATE TABLE titlis_oltp.queue_scorecards (
                queue_scorecard_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                queue_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, overall_score NUMERIC(5,2))""")
            exec("""CREATE TABLE titlis_oltp.validation_rules (
                validation_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                rule_id VARCHAR(50) NOT NULL, pillar VARCHAR(50) NOT NULL, rule_severity VARCHAR(50) NOT NULL,
                weight NUMERIC(5,2) NOT NULL, is_remediable BOOLEAN NOT NULL DEFAULT FALSE)""")
            exec("""CREATE TABLE titlis_oltp.validation_results (
                validation_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                app_scorecard_id BIGINT NOT NULL, validation_rule_id BIGINT NOT NULL,
                rule_passed BOOLEAN NOT NULL, result_message TEXT, actual_value TEXT)""")
            exec("""CREATE TABLE titlis_oltp.queue_validation_results (
                queue_validation_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                queue_scorecard_id BIGINT NOT NULL, rule_id VARCHAR(20) NOT NULL, rule_name VARCHAR(255),
                pillar VARCHAR(50), severity VARCHAR(20), rule_passed BOOLEAN NOT NULL,
                result_message TEXT, actual_value TEXT, evaluated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW())""")

            // service_definitions: team-pag aparece em checkout E onboarding (DAG)
            exec("INSERT INTO titlis_oltp.service_definitions (service_definition_id, tenant_id, service_name, team, product, tier) VALUES " +
                "(10,1,'orders-api','team-pag','checkout','tier-1')," +
                "(20,1,'ledger','team-led','checkout','tier-2')," +
                "(30,1,'signup','team-pag','onboarding','tier-2')")
            exec("INSERT INTO titlis_oltp.workloads (workload_id, workload_name, k8s_uid, service_definition_id, is_active) VALUES " +
                "(1,'orders-api','uid-orders',10,TRUE),(2,'ledger','uid-ledger',20,TRUE),(3,'signup','uid-signup',30,TRUE)")
            // série temporal: orders-api em 2 dias distintos → 2 pontos de tendência
            exec("INSERT INTO titlis_ts.scorecard_scores (workload_id, tenant_id, overall_score, recorded_at) VALUES " +
                "(1,1,40.00,NOW()),(1,1,50.00,DATEADD('DAY',-1,NOW()))")
            exec("INSERT INTO titlis_oltp.app_scorecards (app_scorecard_id, workload_id, tenant_id, overall_score) VALUES " +
                "(1,1,1,40.00),(2,2,1,80.00),(3,3,1,90.00)")  // orders-api tier-1 @40 → piso crítico
            exec("INSERT INTO titlis_oltp.queues (queue_id, tenant_id, display_name, service_definition_id, is_active) VALUES " +
                "(1,1,'orders-events-sub',10,TRUE)")
            exec("INSERT INTO titlis_oltp.queue_scorecards (queue_scorecard_id, queue_id, tenant_id, overall_score) VALUES " +
                "(1,1,1,70.00)")
            exec("INSERT INTO titlis_oltp.validation_rules (validation_rule_id, rule_id, pillar, rule_severity, weight, is_remediable) VALUES " +
                "(100,'SEC-003','SECURITY','CRITICAL',3.00,TRUE)")
            exec("INSERT INTO titlis_oltp.validation_results (app_scorecard_id, validation_rule_id, rule_passed, result_message, actual_value) VALUES " +
                "(1,100,FALSE,'sem network policy','none')")
            exec("INSERT INTO titlis_oltp.queue_validation_results (queue_scorecard_id, rule_id, rule_name, pillar, severity, rule_passed, result_message, actual_value) VALUES " +
                "(1,'QS-001','Backlog','OPERATIONAL','ERROR',FALSE,'backlog alto','999')")
        }
    }

    private fun devHeaders(): Map<String, String> = mapOf(
        "X-Dev-Auth" to "true", "X-Dev-Tenant-Id" to "1", "X-Dev-Roles" to "titlis.admin",
    )

    @Test
    fun `tree depth all monta produtos times servicos com DAG e piso critico`() = testApplication {
        val authenticator = testRequestAuthenticator()
        application {
            installTestSecurity(authenticator)
            reliabilityRoutes(ReliabilityRepository())
        }

        val res = client.get("/v1/reliability/tree?depth=all") { devHeaders().forEach { (k, v) -> header(k, v) } }
        assertEquals(HttpStatusCode.OK, res.status)
        val body = res.bodyAsText()

        assertContains(body, "checkout")
        assertContains(body, "onboarding")
        // DAG: team-pag sob os dois produtos
        assertContains(body, "\"path\":\"checkout/team-pag\"")
        assertContains(body, "\"path\":\"onboarding/team-pag\"")
        // folhas
        assertContains(body, "orders-api")
        assertContains(body, "ledger")
        assertContains(body, "signup")
        // piso crítico (orders-api tier-1 @40)
        assertContains(body, "\"criticalBreach\":true")
    }

    @Test
    fun `tree depth 1 retorna so produtos sem times`() = testApplication {
        val authenticator = testRequestAuthenticator()
        application {
            installTestSecurity(authenticator)
            reliabilityRoutes(ReliabilityRepository())
        }

        val res = client.get("/v1/reliability/tree?depth=1") { devHeaders().forEach { (k, v) -> header(k, v) } }
        assertEquals(HttpStatusCode.OK, res.status)
        val body = res.bodyAsText()
        assertContains(body, "checkout")
        assertFalse(body.contains("team-pag"), "depth=1 não deve expor times")
    }

    @Test
    fun `findings do servico lista workload e queue com pts recuperaveis`() = testApplication {
        val authenticator = testRequestAuthenticator()
        application {
            installTestSecurity(authenticator)
            reliabilityRoutes(ReliabilityRepository())
        }

        val res = client.get("/v1/reliability/services/10/findings") { devHeaders().forEach { (k, v) -> header(k, v) } }
        assertEquals(HttpStatusCode.OK, res.status)
        val body = res.bodyAsText()
        assertContains(body, "SEC-003")
        assertContains(body, "QS-001")
        assertContains(body, "riGainService")
        // deep-link de remediação: o finding de workload carrega o k8s_uid
        assertContains(body, "uid-orders")
    }

    @Test
    fun `trend retorna pontos diarios ponderados por tier`() = testApplication {
        val authenticator = testRequestAuthenticator()
        application {
            installTestSecurity(authenticator)
            reliabilityRoutes(ReliabilityRepository())
        }

        val res = client.get("/v1/reliability/trend?root=checkout/team-pag&days=30") { devHeaders().forEach { (k, v) -> header(k, v) } }
        assertEquals(HttpStatusCode.OK, res.status)
        val body = res.bodyAsText()
        assertContains(body, "\"ri\"")
        assertContains(body, "\"date\"")
        // dois dias distintos → dois pontos
        assertEquals(2, body.split("\"date\"").size - 1)
    }

    @Test
    fun `tree exige autenticacao`() = testApplication {
        val authenticator = testRequestAuthenticator()
        application {
            installTestSecurity(authenticator)
            reliabilityRoutes(ReliabilityRepository())
        }
        val res = client.get("/v1/reliability/tree")
        assertEquals(HttpStatusCode.Unauthorized, res.status)
    }
}
