package io.titlis.api.repository

import io.titlis.api.database.tables.UserFavorites
import kotlinx.coroutines.test.runTest
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.transactions.experimental.newSuspendedTransaction
import org.jetbrains.exposed.sql.transactions.transaction
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class FavoriteRepositoryTest {

    private lateinit var db: Database
    private lateinit var repo: FavoriteRepository

    // IDs resolvidos via raw SQL para evitar incompatibilidade do Exposed DSL com H2 FK columns
    private var tenantId = 0L
    private var userId = 0L
    private var otherUserId = 0L

    @BeforeTest
    fun setup() {
        db = Database.connect(
            url = "jdbc:h2:mem:test_favorites_${System.nanoTime()};DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
            driver = "org.h2.Driver",
        )
        transaction(db) {
            exec("CREATE SCHEMA IF NOT EXISTS titlis_oltp")
            exec("""
                CREATE TABLE IF NOT EXISTS titlis_oltp.tenants (
                    tenant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_name VARCHAR(255) NOT NULL,
                    slug VARCHAR(100) NOT NULL,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    tenant_plan VARCHAR(50) NOT NULL DEFAULT 'free',
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
                )
            """)
            exec("""
                CREATE TABLE IF NOT EXISTS titlis_oltp.platform_users (
                    platform_user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL,
                    email VARCHAR(320) NOT NULL,
                    display_name VARCHAR(255),
                    password_hash TEXT,
                    platform_role VARCHAR(50) NOT NULL DEFAULT 'viewer',
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    is_break_glass BOOLEAN NOT NULL DEFAULT FALSE,
                    last_login_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    deleted_at TIMESTAMP WITH TIME ZONE
                )
            """)
            SchemaUtils.create(UserFavorites)

            exec("INSERT INTO titlis_oltp.tenants (tenant_name, slug) VALUES ('Test Tenant', 'test-tenant')")
            tenantId = exec("SELECT MAX(tenant_id) FROM titlis_oltp.tenants") { rs ->
                if (rs.next()) rs.getLong(1) else 1L
            }!!

            exec("INSERT INTO titlis_oltp.platform_users (tenant_id, email, platform_role) VALUES ($tenantId, 'dev@titlis.local', 'admin')")
            userId = exec("SELECT MAX(platform_user_id) FROM titlis_oltp.platform_users") { rs ->
                if (rs.next()) rs.getLong(1) else 1L
            }!!

            exec("INSERT INTO titlis_oltp.platform_users (tenant_id, email, platform_role) VALUES ($tenantId, 'other@titlis.local', 'viewer')")
            otherUserId = exec("SELECT MAX(platform_user_id) FROM titlis_oltp.platform_users") { rs ->
                if (rs.next()) rs.getLong(1) else 2L
            }!!
        }
        repo = FavoriteRepository()
    }

    private suspend fun <T> dbOp(block: suspend () -> T): T =
        newSuspendedTransaction(db = db) { block() }

    @Test
    fun `add persiste favorito e listFavoriteK8sUids retorna o uid`() = runTest {
        dbOp {
            repo.add(userId, tenantId, "uid-abc")
            val ids = repo.listFavoriteK8sUids(userId, tenantId)
            assertTrue("uid-abc" in ids)
        }
    }

    @Test
    fun `add e idempotente — segunda chamada nao duplica`() = runTest {
        dbOp {
            repo.add(userId, tenantId, "uid-dup")
            repo.add(userId, tenantId, "uid-dup")
            val ids = repo.listFavoriteK8sUids(userId, tenantId)
            assertEquals(1, ids.count { it == "uid-dup" })
        }
    }

    @Test
    fun `remove apaga o favorito`() = runTest {
        dbOp {
            repo.add(userId, tenantId, "uid-remove")
            repo.remove(userId, tenantId, "uid-remove")
            val ids = repo.listFavoriteK8sUids(userId, tenantId)
            assertFalse("uid-remove" in ids)
        }
    }

    @Test
    fun `remove sem favorito nao causa erro`() = runTest {
        dbOp {
            repo.remove(userId, tenantId, "uid-inexistente")
        }
    }

    @Test
    fun `listFavoriteK8sUids retorna apenas favoritos do usuario correto`() = runTest {
        dbOp {
            repo.add(userId, tenantId, "uid-user1")
            repo.add(otherUserId, tenantId, "uid-user2")

            val user1Ids = repo.listFavoriteK8sUids(userId, tenantId)
            val user2Ids = repo.listFavoriteK8sUids(otherUserId, tenantId)

            assertTrue("uid-user1" in user1Ids)
            assertFalse("uid-user2" in user1Ids)
            assertTrue("uid-user2" in user2Ids)
            assertFalse("uid-user1" in user2Ids)
        }
    }

    @Test
    fun `listFavoriteK8sUids retorna conjunto vazio quando sem favoritos`() = runTest {
        dbOp {
            val ids = repo.listFavoriteK8sUids(userId, tenantId)
            assertTrue(ids.isEmpty())
        }
    }

    @Test
    fun `add e remove multiplos favoritos`() = runTest {
        dbOp {
            repo.add(userId, tenantId, "uid-1")
            repo.add(userId, tenantId, "uid-2")
            repo.add(userId, tenantId, "uid-3")
            repo.remove(userId, tenantId, "uid-2")

            val ids = repo.listFavoriteK8sUids(userId, tenantId)
            assertTrue("uid-1" in ids)
            assertFalse("uid-2" in ids)
            assertTrue("uid-3" in ids)
            assertEquals(2, ids.size)
        }
    }
}
