package io.titlis.api.repository

import io.titlis.api.database.tables.Workloads
import io.titlis.api.domain.WorkloadMatchSpec
import kotlinx.coroutines.test.runTest
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.select
import org.jetbrains.exposed.sql.transactions.transaction
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull

class ServiceDefinitionRepositoryTest {

    private lateinit var db: Database
    private val repo = ServiceDefinitionRepository()

    @BeforeTest
    fun setup() {
        db = Database.connect(
            url = "jdbc:h2:mem:test_svcdef_${System.nanoTime()};DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
            driver = "org.h2.Driver",
        )
        transaction(db) {
            exec("CREATE SCHEMA IF NOT EXISTS titlis_oltp")
            exec("CREATE TABLE titlis_oltp.clusters (cluster_id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL)")
            exec(
                "CREATE TABLE titlis_oltp.namespaces (namespace_id BIGINT PRIMARY KEY, " +
                    "cluster_id BIGINT NOT NULL, namespace_name VARCHAR(255) NOT NULL)",
            )
            exec(
                """CREATE TABLE titlis_oltp.workloads (
                    workload_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    namespace_id BIGINT NOT NULL, workload_name VARCHAR(255) NOT NULL,
                    team TEXT, service_definition_id BIGINT, is_active BOOLEAN NOT NULL DEFAULT TRUE)""",
            )
            exec(
                """CREATE TABLE titlis_oltp.service_definitions (
                    service_definition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, service_name TEXT NOT NULL, team TEXT NOT NULL,
                    product TEXT, tier TEXT, description TEXT, repo_url TEXT, raw_yaml TEXT,
                    gitops_paths JSON, remediation JSON, last_seen_at TIMESTAMP WITH TIME ZONE,
                    is_stale BOOLEAN NOT NULL DEFAULT FALSE, synced_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE,
                    CONSTRAINT uq_svc UNIQUE (tenant_id, service_name))""",
            )
            exec(
                """CREATE TABLE titlis_oltp.service_workload_patterns (
                    service_workload_pattern_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, service_definition_id BIGINT NOT NULL,
                    namespaces JSON, name_pattern TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE,
                    CONSTRAINT uq_swp UNIQUE (service_definition_id, name_pattern))""",
            )
            exec(
                """CREATE TABLE titlis_oltp.service_queue_patterns (
                    service_queue_pattern_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, service_definition_id BIGINT NOT NULL,
                    provider VARCHAR(50), pattern VARCHAR(500), match_type VARCHAR(20),
                    match_field VARCHAR(20), created_at TIMESTAMP WITH TIME ZONE)""",
            )

            exec("INSERT INTO titlis_oltp.clusters (cluster_id, tenant_id) VALUES (1, 1)")
            exec(
                "INSERT INTO titlis_oltp.namespaces (namespace_id, cluster_id, namespace_name) VALUES " +
                    "(100, 1, 'orders-prod'), (101, 1, 'other-ns')",
            )
            exec(
                "INSERT INTO titlis_oltp.workloads (workload_id, namespace_id, workload_name, is_active) VALUES " +
                    "(1, 100, 'orders-api', TRUE)," +     // casa (ns + nome)
                    "(2, 100, 'orders-worker', TRUE)," +  // não casa (nome)
                    "(3, 101, 'orders-api', TRUE)",       // não casa (ns fora do filtro)
            )
        }
    }

    private fun teamOf(workloadId: Long): String? = transaction(db) {
        Workloads.select(Workloads.team).where { Workloads.workloadId eq workloadId }
            .single()[Workloads.team]
    }

    private fun sdidOf(workloadId: Long): Long? = transaction(db) {
        Workloads.select(Workloads.serviceDefinitionId).where { Workloads.workloadId eq workloadId }
            .single()[Workloads.serviceDefinitionId]
    }

    @Test
    fun `name_pattern liga apenas workloads que casam namespace e nome`() = runTest {
        repo.upsert(
            tenantId = 1L,
            event = ServiceDefinitionEvent(
                serviceName = "orders-api",
                team = "orders",
                workloadMatch = WorkloadMatchSpec(
                    namespaces = listOf("orders-prod"),
                    namePattern = "^orders-api(-.*)?$",
                ),
            ),
        )

        assertEquals("orders", teamOf(1))
        assertEquals(null, teamOf(2))
        assertEquals(null, teamOf(3))
        assertNull(sdidOf(2))
        assertNull(sdidOf(3))
    }

    @Test
    fun `conflito - pattern mais especifico vence o mais amplo`() = runTest {
        // Definition ampla (sem namespaces, regex genérica) liga primeiro.
        repo.upsert(
            tenantId = 1L,
            event = ServiceDefinitionEvent(
                serviceName = "orders-broad",
                team = "team-broad",
                workloadMatch = WorkloadMatchSpec(namespaces = emptyList(), namePattern = "^orders-.*$"),
            ),
        )
        assertEquals("team-broad", teamOf(1))

        // Definition específica (namespace + nome exato) deve roubar o workload 1.
        repo.upsert(
            tenantId = 1L,
            event = ServiceDefinitionEvent(
                serviceName = "orders-api",
                team = "team-specific",
                workloadMatch = WorkloadMatchSpec(namespaces = listOf("orders-prod"), namePattern = "^orders-api$"),
            ),
        )
        assertEquals("team-specific", teamOf(1))
    }

    @Test
    fun `limpeza - workload que deixa de casar e desligado`() = runTest {
        repo.upsert(
            tenantId = 1L,
            event = ServiceDefinitionEvent(
                serviceName = "orders-api",
                team = "orders",
                workloadMatch = WorkloadMatchSpec(namespaces = listOf("orders-prod"), namePattern = "^orders-api$"),
            ),
        )
        assertEquals("orders", teamOf(1))

        // Mesmo service_definition, pattern alterado que não casa mais o workload 1.
        repo.upsert(
            tenantId = 1L,
            event = ServiceDefinitionEvent(
                serviceName = "orders-api",
                team = "orders",
                workloadMatch = WorkloadMatchSpec(namespaces = listOf("orders-prod"), namePattern = "^payments-.*$"),
            ),
        )
        assertNull(sdidOf(1))
        assertNull(teamOf(1))
    }

    @Test
    fun `compat - sem workload_match usa nome exato`() = runTest {
        repo.upsert(
            tenantId = 1L,
            event = ServiceDefinitionEvent(
                serviceName = "orders-worker",
                team = "legacy-team",
                workloads = listOf("orders-worker"),
            ),
        )

        assertEquals("legacy-team", teamOf(2))
        assertNotNull(sdidOf(2))
        assertNull(teamOf(1))
    }
}
